### ISSUE TITLE
Default trainChr and testChr different to that in docs

### ISSUE THREAD

**Issue by IsmailM** [lulizou/boostme#1]
According to the help: 

Default trainChr == chr3 and Default testChr == chr4

i.e. From here:
https://github.com/lulizou/boostme/blob/8bb65bd82fb9311f05f04b9974b5960d82219ed3/R/boostme.R#L21-L27

However, the code suggests that default trainChr is chr1 and default testChr is chr2:

https://github.com/lulizou/boostme/blob/8bb65bd82fb9311f05f04b9974b5960d82219ed3/R/boostme.R#L82-L87

**Comment by lulizou** [comment]
Thanks for catching this! I just fixed it to be train on chr3 and test on chr4 in both places.
