### ISSUE TITLE
Chromosome requires `chr` and does not work with just the number

### ISSUE THREAD

**Issue by IsmailM** [lulizou/boostme#3]
BoostMe requires the chromosome data to be in the following format `chr1,chr2,chr3..` rather than just `1,2,3...`.

This is due to the following line where you select the autosomes:

https://github.com/lulizou/boostme/blob/4c161da19c5f6b3d180ccf56c1e477ca083e2913/R/boostme.R#L123

As a result, the bs object ends up empty causing the following cryptic error:

```
2020-04-25 16:04:53.216 ... Training the model
Error in if ((maximize && score > best_score) || (!maximize && score <  :
  missing value where TRUE/FALSE needed
```
(I understand the above error line is from XgBoost)

I have fallen into this trap twice over the last year (😄) and ended up spending quite a bit of time debugging both times to get to the root cause. 

As such, it would be most useful if you could add a validation step before this step to catch this issue.

**Comment by lulizou** [comment]
Sorry for the inconvenience! Just added an if statement in there to hopefully take care of that.

**Comment by IsmailM** [comment]
Thanks, that looks perfect 👍

**Comment by nsmackler** [comment]
Can you please update this to work for non-human genomes? So have an argument that is nAutosomes (or something) that can replace 22 in this and the following line?
